import type { Metadata } from "next";
import "./globals.css";
import ClientAuthProvider from "../components/ClientAuthProvider";
import MuiProvider from "../components/MuiProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <MuiProvider>
          <ClientAuthProvider />
          {children}
        </MuiProvider>
      </body>
    </html>
  );
}
